[package]
name = "37529/oxygen-was-my-dream"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
iris = "michael-48/iris@2.3.1"
gizmo = "bosschaz1010/gizmo@1.0.0"
react = "jsdotlua/react@17.2.1"
react-roblox = "jsdotlua/react-roblox@17.2.1"
virtualized-list = "jsdotlua/virtualized-list@1.3.6"