return {
    Vault = "rbxassetid://",
    Wallclimb = "rbxassetid://",
    Dropkick = "rbxassetid://",
    Fall = {
        [0] = { -- [Studs]
            [1] = "rbxasssetid://",
            [2] = "rbxasssetid://",
            [3] = "rbxasssetid://",
        },
        [200] = { -- [Studs] 
            [1] = "rbxasssetid://",
            [2] = "rbxasssetid://",
            [3] = "rbxasssetid://",
        }
    }
}